### ISSUE TITLE
Performance in large directories

### ISSUE THREAD

**Issue by uncenter** [yassinebridi/serpl#14]
Understandably running a program that searches in thousands of files across a massive directory is bad for performance but I wonder if there are ways to improve how it at least appears in the UI, or hopefully even some genuine improvements to grepping files and searching them more efficiently! I first noticed this on https://github.com/NixOS/nixpkgs, so you can test it out for yourself there if you are willing to clone the whole thing 😅

**Comment by yassinebridi** [comment]
Thanks for the report.
I'm aware of the issue, and it's mainly because of the on key press search, it spawns multiple `ripgrep` instances.

i'm looking into other ways of enhancing this behavior.
- debounce input
- only search when you click enter(configurable, to turn on and off)

**Comment by uncenter** [comment]
> only search when you click enter(configurable, to turn on and off)

I like this! Maybe it could be dynamic / auto-trigger if there are too many files and display some sort of notification to alert the user?

**Comment by yassinebridi** [comment]
I like that, i will:

- debounce input (this is good in any case imo)
- only search when you click enter if the folder is big, and display a notification that you have to click enter to search

That click enter thing is already implemented for non git folders, but a better solution is to do it for any big folder.

**Comment by yassinebridi** [comment]
I have pushed a new version fixing this.
